# Clarity DB credentials. You can find them through heroku or ask an engineer for the Read-only credentials
database:
  host:     ''
  port:     5432
  dbname:   ''
  user:     'support'
  password: ''

# Questionnaire builder login credentials. This uses your Clarity login credentials
web:
  login:
    url:      'https://qb.brightbytes.net/users/sign_in'
    username: ''
    password: ''
  download:
    url_template: 'http://qb.brightbytes.net/campaigns/:id/responses.csv'
